
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALFNUM APLICAR APPEND APPLY CONS DECIMAL DIVIDE FIRST LCOR LPAREN MAX MIN MINUS MODULO NUMERO OPSLAH PLUS QUOTE RCOR REST RPAREN STRING TIMESexpresion_apply : LPAREN words QUOTE expresion QUOTE lista RPAREN words : APPLY\n               | APLICAR\n\n    expresion : operador\n                 | funcion operador : PLUS\n               | MINUS\n               | TIMES\n               | DIVIDE\n               | OPSLAH\n               | MODULOfuncion : MAX\n               | MIN\n               | CONS\n               | APPEND\n               | FIRST\n               | RESTlista : LPAREN RPAREN\n             | LPAREN atomo RPAREN\n             | LPAREN atomo atomo RPAREN\n             | LPAREN atomo atomo atomo RPAREN\n             | LPAREN atomo atomo atomo atomo RPAREN\n             | LPAREN atomo atomo atomo atomo atomo RPAREN\n             | LPAREN lista lista RPAREN\n             | LPAREN lista atomo RPAREN\n             | LPAREN atomo lista RPAREN\n             | LCOR atomo atomo RCOR\n              atomo : DECIMAL\n             | NUMERO\n\n\n    '
    
_lr_action_items = {'LPAREN':([0,22,23,26,27,28,29,30,34,40,41,42,43,44,46,48,49,],[2,23,23,-18,23,23,-28,-29,-19,-20,-26,-24,-25,-27,-21,-22,-23,]),'$end':([1,31,],[0,-1,]),'APPLY':([2,],[4,]),'APLICAR':([2,],[5,]),'QUOTE':([3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,],[6,-2,-3,22,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,]),'PLUS':([6,],[10,]),'MINUS':([6,],[11,]),'TIMES':([6,],[12,]),'DIVIDE':([6,],[13,]),'OPSLAH':([6,],[14,]),'MODULO':([6,],[15,]),'MAX':([6,],[16,]),'MIN':([6,],[17,]),'CONS':([6,],[18,]),'APPEND':([6,],[19,]),'FIRST':([6,],[20,]),'REST':([6,],[21,]),'LCOR':([22,23,26,27,28,29,30,34,40,41,42,43,44,46,48,49,],[25,25,-18,25,25,-28,-29,-19,-20,-26,-24,-25,-27,-21,-22,-23,]),'RPAREN':([23,24,26,27,29,30,33,34,35,36,37,39,40,41,42,43,44,45,46,47,48,49,],[26,31,-18,34,-28,-29,40,-19,41,42,43,46,-20,-26,-24,-25,-27,48,-21,49,-22,-23,]),'DECIMAL':([23,25,26,27,28,29,30,32,33,34,39,40,41,42,43,44,45,46,48,49,],[29,29,-18,29,29,-28,-29,29,29,-19,29,-20,-26,-24,-25,-27,29,-21,-22,-23,]),'NUMERO':([23,25,26,27,28,29,30,32,33,34,39,40,41,42,43,44,45,46,48,49,],[30,30,-18,30,30,-28,-29,30,30,-19,30,-20,-26,-24,-25,-27,30,-21,-22,-23,]),'RCOR':([29,30,38,],[-28,-29,44,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion_apply':([0,],[1,]),'words':([2,],[3,]),'expresion':([6,],[7,]),'operador':([6,],[8,]),'funcion':([6,],[9,]),'lista':([22,23,27,28,],[24,28,35,36,]),'atomo':([23,25,27,28,32,33,39,45,],[27,32,33,37,38,39,45,47,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion_apply","S'",1,None,None,None),
  ('expresion_apply -> LPAREN words QUOTE expresion QUOTE lista RPAREN','expresion_apply',7,'p_expresion_apply','yacc.py',10),
  ('words -> APPLY','words',1,'p_words','yacc.py',15),
  ('words -> APLICAR','words',1,'p_words','yacc.py',16),
  ('expresion -> operador','expresion',1,'p_expresion','yacc.py',21),
  ('expresion -> funcion','expresion',1,'p_expresion','yacc.py',22),
  ('operador -> PLUS','operador',1,'p_operador','yacc.py',25),
  ('operador -> MINUS','operador',1,'p_operador','yacc.py',26),
  ('operador -> TIMES','operador',1,'p_operador','yacc.py',27),
  ('operador -> DIVIDE','operador',1,'p_operador','yacc.py',28),
  ('operador -> OPSLAH','operador',1,'p_operador','yacc.py',29),
  ('operador -> MODULO','operador',1,'p_operador','yacc.py',30),
  ('funcion -> MAX','funcion',1,'p_funcion','yacc.py',34),
  ('funcion -> MIN','funcion',1,'p_funcion','yacc.py',35),
  ('funcion -> CONS','funcion',1,'p_funcion','yacc.py',36),
  ('funcion -> APPEND','funcion',1,'p_funcion','yacc.py',37),
  ('funcion -> FIRST','funcion',1,'p_funcion','yacc.py',38),
  ('funcion -> REST','funcion',1,'p_funcion','yacc.py',39),
  ('lista -> LPAREN RPAREN','lista',2,'p_lista','yacc.py',41),
  ('lista -> LPAREN atomo RPAREN','lista',3,'p_lista','yacc.py',42),
  ('lista -> LPAREN atomo atomo RPAREN','lista',4,'p_lista','yacc.py',43),
  ('lista -> LPAREN atomo atomo atomo RPAREN','lista',5,'p_lista','yacc.py',44),
  ('lista -> LPAREN atomo atomo atomo atomo RPAREN','lista',6,'p_lista','yacc.py',45),
  ('lista -> LPAREN atomo atomo atomo atomo atomo RPAREN','lista',7,'p_lista','yacc.py',46),
  ('lista -> LPAREN lista lista RPAREN','lista',4,'p_lista','yacc.py',47),
  ('lista -> LPAREN lista atomo RPAREN','lista',4,'p_lista','yacc.py',48),
  ('lista -> LPAREN atomo lista RPAREN','lista',4,'p_lista','yacc.py',49),
  ('lista -> LCOR atomo atomo RCOR','lista',4,'p_lista','yacc.py',50),
  ('atomo -> DECIMAL','atomo',1,'p_atomo','yacc.py',56),
  ('atomo -> NUMERO','atomo',1,'p_atomo','yacc.py',57),
]
